version: '3.2'
services:

  web:
    image: kv:latest
    container_name: kv_web
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
      args:
        RUBY_VERSION: '2.5.1'
        PG_MAJOR: '11'
        NODE_MAJOR: '12'
        YARN_VERSION: '1.22.4'
        BUNDLER_VERSION: '2.0.2'
    tmpfs:
      - /tmp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 5000 -b 0.0.0.0"
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - assets:/app/public/assets
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis 
    env_file:
      - ./.dockerdev/.env.docker
    links:
      - mailcatcher
      
  postgres:
    container_name: kv_db
    image: postgres:11.1
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432
    ports:
      - 5432    
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.2
      interval: 5s

  redis:
    container_name: kv_redis
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30  

  sidekiq:
    image: kv:latest
    container_name: kv_sidekiq
    stdin_open: true
    tty: true
    depends_on:
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - ./.dockerdev/.env.docker

  webpacker:
    image: kv:latest
    container_name: kv_webpacker
    stdin_open: true
    tty: true
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - assets:/app/public/assets
    ports:
      - "3037:3035"
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  mailcatcher:
    container_name: kv_mailer
    image: yappabe/mailcatcher
    ports:
      - "1026:1025"
      - "1081:1080"


volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
  assets: